title: Hazaq
email: hazaq.naeem@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  All things Linux | OpenSource Software | Redhat | AWS | DevOps | Zimbra
baseurl: "" # the subpath of your site, e.g. /blog
url: "hazaq.me" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: hazaq-me
github_username:  hazaq

google_analytics: UA-113455437-1
linkedin: hazaq-me
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  redirects:
    output: true

defaults:
  -
    scope:
      type: redirects
    values:
      layout: redirect

exclude:
        - CNAME
        - Gemfile.lock
        - Gemfile
